### ISSUE TITLE
carte SD du support intégré à Luna n'ai pas montée pour les sauvegardes

### ISSUE THREAD

**Issue by PhilDroi** [jeedom/plugin-luna#38]
Bonjour,
La carte SD du support intégré à Luna n'est pas montée lorsqu'elle est activée par le plugin, alors que dans l'interface elle apparaît comme activée, la sauvegarde se faisant vers /media
En réalité, la sauvegarde se fait dans le dossier /media du eMMC et donne donc l'impression que tout fonctionne pour l'utilisateur, sauf que la carte SD est vide.
Tout fonctionne bien à condition de la monter à la main sur /media, après l'avoir activée dans le plugin.
Un contournement provisoire étant de la monter au travers du plugin script sur l'évènement  #start#
merci pour les corrections à venir

**Comment by rocket13011** [comment]
https://github.com/jeedom/plugin-luna/commit/0627f9e56749d83f008837d83af70413148f583b

**Comment by PhilDroi** [comment]
Bonjour, super !, merci
par contre j'avais vu ceci aussi sur ces fonctions, je ne pense pas que 'unmount' soit supporté par le bash, mais plutôt 'umount', bon ce n'est qu'une sécu et pas bloquant.
Je ne suis pas sur la branche beta avec le plugin luna, est-ce que j'y  passe pour tester ? est-ce à moi de fermer l'issue ?
merci pour tout

 public static function partitionSD() {
    $sdSector = "/dev/mmcblk2";
    exec('sudo **unmount** ' . $sdSector);


  public static function mountSD() {
    $sdSector = "/dev/mmcblk2";
    $montage = "/media";
    if (self::isMountedSD()) {
      return;
    }
    exec('sudo **unmount** ' . $sdSector);
